### ISSUE TITLE
PSET 01_Cash project

### ISSUE THREAD

**Issue by vinhthien19292** [mareksuscak/cs50#4]
I finished my codes for the "Cash" in the problem set 1. It ran well except when I tried 0.42 or other values less than 0.2. 

I would be very appreciated if anyone can help me with this problem? The code is provided below.

Thank you a lot.

`#include <cs50.h>
#include <stdio.h>
#include <math.h>

int main(void)
{
    int amount;
    int pennies;
    int dime;
    int nickle;
    int quarter; 
        
    do
    {
        float received_money = get_float("Money received: ");
        amount = received_money * 100;
    }    
        while (amount <= 0);
        do    
        {
            quarter = amount/25;           
        }
        while (quarter > 25);
                    
            do
            {
                dime = (amount%25)/10;                
            }
            while (dime > 10);
                
                do
                {
                    nickle =  ((amount%25)%10)/5;                    
                }
                while (nickle > 5);
        
                    do
                    {
                        pennies = (((amount%25)%10)%5);                        
                    }
                    while (pennies > 1);                                        
    printf ("Cashout: %i\n", pennies + dime + nickle + quarter);
    
}
`

**Comment by rajan9519** [comment]
Plz send problem statement.

**Comment by vinhthien19292** [comment]
It did not show any message. 
When I ran the program, input the number 0.42

Cash recieved: 0.42
|

The program just stood still without sending in any results or message.

**Comment by rajan9519** [comment]
Because in first do-while loop the terminating condition is wrong because
that amount is never going to be a negative number .

**Comment by rajan9519** [comment]
Don't use do while loop.
You can do the same by if and else statement.

**Comment by vinhthien19292** [comment]
Can you help me fix the loop "while - do" and change it to "if - else"? I tried the If (amount > 0) then do all the loops under but still got bug with 0.42 value.

Thank you

**Comment by rajan9519** [comment]
Will it be fine for you if i will help you in evening.
And plz do remind me for this if i forgot to reply you.

**Comment by vinhthien19292** [comment]
Sure Rajan. It is very kind of you to support me. I am a newbie to programming and is still very messy with loops.

**Comment by rajan9519** [comment]
#include<cs50.h>
#include <stdio.h>
#include <math.h>
int main(void)
{
int amount;
int pennies;
int dime;
int nickle;
int quarter;
int amount_remaining;
do
{
float received_money = get_float("Money received: ");
    amount = received_money * 100;
}while (amount <= 0);

amount_remaining = amount;

quarter = amount/25;
amount_remaining = amount_remaining%25;

dime = amount_remaining/10;
amount_remaining = amount_remaining%10;

nickle =  amount_remaining/5;
amount_remaining = amount_remaining%5;

pennies = amount_remaining;

printf ("Cashout: %i\n", pennies + dime + nickle + quarter);
}

**Comment by rajan9519** [comment]
this may help you. feel free to ask any doubt regarding this and any other
problem.

**Comment by vinhthien19292** [comment]
Great Rajan!

1 loop needed only! I got your idea. Many thanks Rajan!

**Comment by rajan9519** [comment]
your welcome , well what is your name and where are you from?

**Comment by vinhthien19292** [comment]
My name is Thien and I am from Vietnam. I am currently working in the equity investment industry and now trying to get a bit of quantitative finance. So I take the course computer science to get some "common sense" of this new area.
