### ISSUE TITLE
Finance Issue

### ISSUE THREAD

**Issue by emre570** [mareksuscak/cs50#9]
When i submit the finance task, i take an error says: /check route confirms whether username is available. Can you guys help me please?

**Comment by mareksuscak** [comment]
@emre570 please note I have not updated the solutions for CS50 2020 batch. There's a chance that the task description and/or requirements have changed.

**Comment by emre570** [comment]
Alright, thanks for the answer. I will follow if you update the solutions.

**Comment by mareksuscak** [comment]
Thanks @emre570. I've been meaning to update the solutions for some time now but wasn't able to find the time.
